// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA57_Ni4j3MVpRjnWvf99KW3cyl922F_GQ',
    appId: '1:580851353325:web:7172d072244dba16eb6ee4',
    messagingSenderId: '580851353325',
    projectId: 'e-bookapp-bcb90',
    authDomain: 'e-bookapp-bcb90.firebaseapp.com',
    storageBucket: 'e-bookapp-bcb90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4O6ExI23f1R3gewRfwdXxBiDvIZjQLg',
    appId: '1:520239393789:android:39c6739ede3d53ff3b0794',
    messagingSenderId: '520239393789',
    projectId: 'e-book-71338',
    storageBucket: 'e-book-71338.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ8EWsBds829OE8rSE-8Cl1_D1kUODUo0',
    appId: '1:580851353325:ios:56ac7b7d85ad604beb6ee4',
    messagingSenderId: '580851353325',
    projectId: 'e-bookapp-bcb90',
    storageBucket: 'e-bookapp-bcb90.appspot.com',
    iosBundleId: 'com.example.eBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ8EWsBds829OE8rSE-8Cl1_D1kUODUo0',
    appId: '1:580851353325:ios:ce9de2d156b3bbebeb6ee4',
    messagingSenderId: '580851353325',
    projectId: 'e-bookapp-bcb90',
    storageBucket: 'e-bookapp-bcb90.appspot.com',
    iosBundleId: 'com.example.eBookApp.RunnerTests',
  );
}
